using System.Text;
using System.Text.RegularExpressions;
using ConverterApp.Models;

namespace ConverterApp.Converters.WinForms2All;

/// <summary>
/// Converts WinForms Designer code (InitializeComponent-style C#) to HTML/CSS/JS,
/// MAUI XAML/C#, or Unity C# MonoBehaviour UI.
/// </summary>
public partial class WinFormsConverter
{
    private readonly ConversionOptions _opts;

    public WinFormsConverter(ConversionOptions? options = null)
        => _opts = options ?? new ConversionOptions();

    // ──────────────────────────────────────────────────────────────────────────
    //  Entry points
    // ──────────────────────────────────────────────────────────────────────────

    public ConversionResult ToHtml(string winFormsCs)
        => ConvertTo(winFormsCs, WinFormsTarget.Html);

    public ConversionResult ToMaui(string winFormsCs)
        => ConvertTo(winFormsCs, WinFormsTarget.Maui);

    public ConversionResult ToUnity(string winFormsCs)
        => ConvertTo(winFormsCs, WinFormsTarget.Unity);

    // ──────────────────────────────────────────────────────────────────────────
    //  Core conversion
    // ──────────────────────────────────────────────────────────────────────────

    private ConversionResult ConvertTo(string cs, WinFormsTarget target)
    {
        if (string.IsNullOrWhiteSpace(cs))
            return ConversionResult.Fail("WinForms C# source is empty.");

        var warnings = new List<string>();
        var controls = ParseWinFormsControls(cs, warnings);
        var formProps = ParseFormProperties(cs);

        return target switch
        {
            WinFormsTarget.Html   => GenerateHtml(controls, formProps, warnings),
            WinFormsTarget.Maui   => GenerateMaui(controls, formProps, warnings),
            WinFormsTarget.Unity  => GenerateUnity(controls, formProps, warnings),
            _ => ConversionResult.Fail("Unknown target."),
        };
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  WinForms → HTML
    // ──────────────────────────────────────────────────────────────────────────

    private static ConversionResult GenerateHtml(
        List<WinFormsControl> controls,
        Dictionary<string, string> formProps,
        List<string> warnings)
    {
        var htmlSb = new StringBuilder();
        var cssSb  = new StringBuilder();
        var jsSb   = new StringBuilder();

        var formTitle = formProps.TryGetValue("Text", out var ft) ? ft : "Form";
        var formW     = formProps.TryGetValue("ClientSize.Width",  out var fw) ? fw : "800";
        var formH     = formProps.TryGetValue("ClientSize.Height", out var fh) ? fh : "600";

        cssSb.AppendLine("/* Generated by Converter – WinForms to HTML */");
        cssSb.AppendLine($".form-container {{ width: {formW}px; min-height: {formH}px; position: relative; font-family: Segoe UI, sans-serif; }}");
        cssSb.AppendLine();

        jsSb.AppendLine("// Generated by Converter – WinForms to JavaScript");
        jsSb.AppendLine();

        htmlSb.AppendLine($"<div class=\"form-container\" id=\"mainForm\">");

        foreach (var ctrl in controls)
        {
            var htmlEl = WinFormsToHtmlElement(ctrl);
            if (htmlEl == null) { warnings.Add($"No HTML mapping for WinForms control {ctrl.Type}"); continue; }

            // Inline positioning CSS
            var posStyle = $"position: absolute; left: {ctrl.Location.X}px; top: {ctrl.Location.Y}px; " +
                           $"width: {ctrl.Size.Width}px; height: {ctrl.Size.Height}px;";

            cssSb.AppendLine($"#{ctrl.Name} {{ {posStyle} {BuildCssFromWinForms(ctrl)} }}");

            // HTML element
            htmlSb.AppendLine($"  {htmlEl}");

            // JS event handlers
            foreach (var ev in ctrl.Events)
            {
                var jsHandler = MapWinFormsEventToJs(ev.Key);
                jsSb.AppendLine($"document.getElementById('{ctrl.Name}').{jsHandler} = function(event) {{");
                jsSb.AppendLine($"  // {ev.Value}");
                jsSb.AppendLine("};");
                jsSb.AppendLine();
            }
        }

        htmlSb.AppendLine("</div>");

        var fullHtml = $"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{HtmlEncode(formTitle)}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
{htmlSb}
  <script src="app.js"></script>
</body>
</html>
""";

        return ConversionResult.Ok(
            new Dictionary<string, string>
            {
                ["index.html"] = fullHtml,
                ["styles.css"] = cssSb.ToString(),
                ["app.js"]     = jsSb.ToString(),
            },
            warnings);
    }

    private static string? WinFormsToHtmlElement(WinFormsControl ctrl)
    {
        var id = $"id=\"{ctrl.Name}\"";
        return ctrl.Type.ToLowerInvariant() switch
        {
            "button"      => $"<button {id}>{HtmlEncode(ctrl.Text)}</button>",
            "label"       => $"<label {id}>{HtmlEncode(ctrl.Text)}</label>",
            "textbox"     => $"<input type=\"text\" {id} value=\"{HtmlEncode(ctrl.Text)}\" />",
            "richtextbox" => $"<textarea {id}>{HtmlEncode(ctrl.Text)}</textarea>",
            "checkbox"    => $"<input type=\"checkbox\" {id} {(ctrl.Checked ? "checked" : "")} /><label>{HtmlEncode(ctrl.Text)}</label>",
            "radiobutton" => $"<input type=\"radio\" {id} {(ctrl.Checked ? "checked" : "")} /><label>{HtmlEncode(ctrl.Text)}</label>",
            "combobox"    => BuildHtmlComboBox(ctrl),
            "listbox"     => BuildHtmlListBox(ctrl),
            "picturebox"  => $"<img {id} src=\"{HtmlEncode(ctrl.ImagePath)}\" alt=\"{HtmlEncode(ctrl.Text)}\" />",
            "progressbar" => $"<progress {id} value=\"{ctrl.Value}\" max=\"{ctrl.Maximum}\"></progress>",
            "trackbar"    => $"<input type=\"range\" {id} value=\"{ctrl.Value}\" min=\"{ctrl.Minimum}\" max=\"{ctrl.Maximum}\" />",
            "datetimepicker" => $"<input type=\"datetime-local\" {id} />",
            "numericupdown" => $"<input type=\"number\" {id} value=\"{ctrl.Value}\" min=\"{ctrl.Minimum}\" max=\"{ctrl.Maximum}\" />",
            "groupbox"    => $"<fieldset {id}><legend>{HtmlEncode(ctrl.Text)}</legend></fieldset>",
            "panel"       => $"<div {id}></div>",
            "tabcontrol"  => $"<div {id} class=\"tab-control\"></div>",
            "menustrip" or "toolstrip" => $"<nav {id}></nav>",
            "statusstrip" => $"<footer {id}></footer>",
            "datagridview"=> $"<table {id}></table>",
            "listview"    => $"<ul {id}></ul>",
            "treeview"    => $"<ul {id} class=\"tree-view\"></ul>",
            "webbrowser"  => $"<iframe {id}></iframe>",
            _ => $"<div {id}>{HtmlEncode(ctrl.Text)}</div>",
        };
    }

    private static string BuildHtmlComboBox(WinFormsControl ctrl)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"<select id=\"{ctrl.Name}\">");
        foreach (var item in ctrl.Items)
            sb.AppendLine($"  <option>{HtmlEncode(item)}</option>");
        sb.AppendLine("</select>");
        return sb.ToString().TrimEnd();
    }

    private static string BuildHtmlListBox(WinFormsControl ctrl)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"<select id=\"{ctrl.Name}\" size=\"5\"{(ctrl.MultiSelect ? " multiple" : "")}>");
        foreach (var item in ctrl.Items)
            sb.AppendLine($"  <option>{HtmlEncode(item)}</option>");
        sb.AppendLine("</select>");
        return sb.ToString().TrimEnd();
    }

    private static string BuildCssFromWinForms(WinFormsControl ctrl)
    {
        var parts = new List<string>();
        if (!string.IsNullOrEmpty(ctrl.ForeColor)) parts.Add($"color: {ctrl.ForeColor}");
        if (!string.IsNullOrEmpty(ctrl.BackColor)) parts.Add($"background-color: {ctrl.BackColor}");
        if (ctrl.FontSize > 0) parts.Add($"font-size: {ctrl.FontSize}pt");
        if (ctrl.FontBold) parts.Add("font-weight: bold");
        if (ctrl.FontItalic) parts.Add("font-style: italic");
        return string.Join("; ", parts) + (parts.Count > 0 ? ";" : "");
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  WinForms → MAUI
    // ──────────────────────────────────────────────────────────────────────────

    private ConversionResult GenerateMaui(
        List<WinFormsControl> controls,
        Dictionary<string, string> formProps,
        List<string> warnings)
    {
        var xamlSb = new StringBuilder();
        var csSb   = new StringBuilder();

        xamlSb.AppendLine($"""
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="{_opts.MauiXmlns}"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="{_opts.AppNamespace}.MainPage"
             Title="{formProps.GetValueOrDefault("Text", "Main Page")}">
    <ScrollView>
        <AbsoluteLayout>
""");

        foreach (var ctrl in controls)
        {
            var mauiEl = WinFormsToMauiElement(ctrl, warnings);
            if (mauiEl != null)
                xamlSb.AppendLine($"            {mauiEl}");
        }

        xamlSb.AppendLine("""
        </AbsoluteLayout>
    </ScrollView>
</ContentPage>
""");

        csSb.AppendLine($$"""
using Microsoft.Maui.Controls;

namespace {{_opts.AppNamespace}};

public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

""");

        foreach (var ctrl in controls)
        {
            foreach (var ev in ctrl.Events)
            {
                var mauiEvent = MapWinFormsEventToMaui(ev.Key);
                csSb.AppendLine($"    private void On{ctrl.Name.ToPascalCase()}_{mauiEvent}(object? sender, EventArgs e)");
                csSb.AppendLine("    {");
                csSb.AppendLine($"        // TODO: {ev.Value}");
                csSb.AppendLine("    }");
                csSb.AppendLine();
            }
        }
        csSb.AppendLine("}");

        return ConversionResult.Ok(
            new Dictionary<string, string>
            {
                ["MainPage.xaml"]    = xamlSb.ToString(),
                ["MainPage.xaml.cs"] = csSb.ToString(),
            },
            warnings);
    }

    private static string? WinFormsToMauiElement(WinFormsControl ctrl, List<string> warnings)
    {
        var pos = $"AbsoluteLayout.LayoutBounds=\"{ctrl.Location.X},{ctrl.Location.Y},{ctrl.Size.Width},{ctrl.Size.Height}\" " +
                  $"AbsoluteLayout.LayoutFlags=\"None\"";
        var name = $"x:Name=\"{ctrl.Name}\"";
        var text = string.IsNullOrEmpty(ctrl.Text) ? "" : $"Text=\"{XmlEscape(ctrl.Text)}\"";

        return ctrl.Type.ToLowerInvariant() switch
        {
            "button"       => $"<Button {name} {text} {pos} />",
            "label"        => $"<Label {name} {text} {pos} />",
            "textbox"      => $"<Entry {name} Text=\"{XmlEscape(ctrl.Text)}\" {pos} />",
            "richtextbox"  => $"<Editor {name} Text=\"{XmlEscape(ctrl.Text)}\" {pos} />",
            "checkbox"     => $"<CheckBox {name} IsChecked=\"{ctrl.Checked}\" {pos} />",
            "radiobutton"  => $"<RadioButton {name} Content=\"{XmlEscape(ctrl.Text)}\" IsChecked=\"{ctrl.Checked}\" {pos} />",
            "combobox"     => $"<Picker {name} {pos} />",
            "listbox"      => $"<ListView {name} {pos} />",
            "picturebox"   => $"<Image {name} Source=\"{XmlEscape(ctrl.ImagePath)}\" {pos} />",
            "progressbar"  => $"<ProgressBar {name} Progress=\"{ctrl.Value / Math.Max(ctrl.Maximum, 1.0):F2}\" {pos} />",
            "trackbar"     => $"<Slider {name} Value=\"{ctrl.Value}\" Minimum=\"{ctrl.Minimum}\" Maximum=\"{ctrl.Maximum}\" {pos} />",
            "datetimepicker"=> $"<DatePicker {name} {pos} />",
            "numericupdown"=> $"<Entry {name} Keyboard=\"Numeric\" Text=\"{ctrl.Value}\" {pos} />",
            "groupbox"     => $"<Border {name} {pos}><Label Text=\"{XmlEscape(ctrl.Text)}\" /></Border>",
            "panel"        => $"<VerticalStackLayout {name} {pos} />",
            "datagridview" => $"<CollectionView {name} {pos} />",
            "listview"     => $"<ListView {name} {pos} />",
            "webbrowser"   => $"<WebView {name} {pos} />",
            _ => null,
        };
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  WinForms → Unity
    // ──────────────────────────────────────────────────────────────────────────

    private ConversionResult GenerateUnity(
        List<WinFormsControl> controls,
        Dictionary<string, string> formProps,
        List<string> warnings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Auto-generated Unity UI manager from WinForms source.
/// Attach this MonoBehaviour to your Canvas GameObject.
/// </summary>
public class FormManager : MonoBehaviour
{
""");

        // Fields
        foreach (var ctrl in controls)
        {
            var unityType = WinFormsToUnityType(ctrl.Type);
            if (!string.IsNullOrEmpty(unityType))
                sb.AppendLine($"    [SerializeField] private {unityType} {ctrl.Name};");
        }

        sb.AppendLine();
        sb.AppendLine("    private void Awake()");
        sb.AppendLine("    {");
        foreach (var ctrl in controls)
        {
            foreach (var ev in ctrl.Events)
            {
                var unityEv = MapWinFormsEventToUnity(ev.Key, ctrl.Type);
                if (!string.IsNullOrEmpty(unityEv))
                {
                    sb.AppendLine($"        {ctrl.Name}.{unityEv}.AddListener(On{ctrl.Name.ToPascalCase()}_{ev.Key});");
                }
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        // Event handlers
        foreach (var ctrl in controls)
        {
            foreach (var ev in ctrl.Events)
            {
                var unityEv = MapWinFormsEventToUnity(ev.Key, ctrl.Type);
                var paramType = unityEv?.Contains("ValueChanged") == true ? "float value" : "";
                sb.AppendLine($"    private void On{ctrl.Name.ToPascalCase()}_{ev.Key}({paramType})");
                sb.AppendLine("    {");
                sb.AppendLine($"        // TODO: {ev.Value}");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");

        return ConversionResult.Ok(
            new Dictionary<string, string> { ["FormManager.cs"] = sb.ToString() },
            warnings);
    }

    private static string WinFormsToUnityType(string winFormsType) =>
        winFormsType.ToLowerInvariant() switch
        {
            "button"       => "Button",
            "label"        => "TMP_Text",
            "textbox"      => "TMP_InputField",
            "richtextbox"  => "TMP_InputField",
            "checkbox"     => "Toggle",
            "radiobutton"  => "Toggle",
            "combobox"     => "TMP_Dropdown",
            "listbox"      => "TMP_Dropdown",
            "progressbar"  => "Slider",
            "trackbar"     => "Slider",
            "picturebox"   => "Image",
            "panel"        => "RectTransform",
            _ => string.Empty,
        };

    private static string MapWinFormsEventToUnity(string ev, string ctrlType) =>
        (ev.ToLowerInvariant(), ctrlType.ToLowerInvariant()) switch
        {
            ("click", "button")     => "onClick",
            ("click", _)            => "onClick",
            ("checkedchanged", _)   => "onValueChanged",
            ("valuechanged", _)     => "onValueChanged",
            ("textchanged", _)      => "onValueChanged",
            ("selectedindexchanged", _) => "onValueChanged",
            _ => string.Empty,
        };

    // ──────────────────────────────────────────────────────────────────────────
    //  WinForms C# parser
    // ──────────────────────────────────────────────────────────────────────────

    private static List<WinFormsControl> ParseWinFormsControls(string cs, List<string> warnings)
    {
        var controls = new Dictionary<string, WinFormsControl>(StringComparer.OrdinalIgnoreCase);

        // Detect control declarations: private System.Windows.Forms.Button button1;
        foreach (Match m in CtrlDeclarationRegex().Matches(cs))
        {
            var type = m.Groups[1].Value;
            var name = m.Groups[2].Value;
            controls[name] = new WinFormsControl { Type = type, Name = name };
        }

        // Parse property assignments: this.button1.Text = "OK";
        foreach (Match m in PropAssignRegex().Matches(cs))
        {
            var ctrl = m.Groups[1].Value;
            var prop = m.Groups[2].Value;
            var val  = m.Groups[3].Value.Trim('"');

            if (!controls.TryGetValue(ctrl, out var c)) continue;

            switch (prop.ToLowerInvariant())
            {
                case "text":      c.Text = val; break;
                case "location":  c.Location = ParsePoint(val); break;
                case "size":      c.Size = ParseSize(val); break;
                case "forecolor": c.ForeColor = ConvertWinFormsColor(val); break;
                case "backcolor": c.BackColor = ConvertWinFormsColor(val); break;
                case "checked":   c.Checked = val.Equals("true", StringComparison.OrdinalIgnoreCase); break;
                case "enabled":   c.Enabled = val.Equals("true", StringComparison.OrdinalIgnoreCase); break;
                case "visible":   c.Visible = val.Equals("true", StringComparison.OrdinalIgnoreCase); break;
                case "value":     if (double.TryParse(val, out var dv)) c.Value = dv; break;
                case "minimum":   if (double.TryParse(val, out var dmin)) c.Minimum = dmin; break;
                case "maximum":   if (double.TryParse(val, out var dmax)) c.Maximum = dmax; break;
            }
        }

        // Parse font assignments
        foreach (Match m in FontRegex().Matches(cs))
        {
            var ctrl = m.Groups[1].Value;
            var family = m.Groups[2].Value;
            var size = m.Groups[3].Value;
            var style = m.Groups[4].Value;

            if (!controls.TryGetValue(ctrl, out var c)) continue;
            c.FontFamily = family;
            if (float.TryParse(size, out var fs)) c.FontSize = fs;
            c.FontBold   = style.Contains("Bold",   StringComparison.OrdinalIgnoreCase);
            c.FontItalic = style.Contains("Italic", StringComparison.OrdinalIgnoreCase);
        }

        // Parse event subscriptions: this.button1.Click += new EventHandler(button1_Click);
        foreach (Match m in EventSubscriptionRegex().Matches(cs))
        {
            var ctrl    = m.Groups[1].Value;
            var evName  = m.Groups[2].Value;
            var handler = m.Groups[3].Value;

            if (controls.TryGetValue(ctrl, out var c))
                c.Events[evName] = handler;
        }

        return controls.Values.OrderBy(c => c.Location.Y).ThenBy(c => c.Location.X).ToList();
    }

    private static Dictionary<string, string> ParseFormProperties(string cs)
    {
        var props = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (Match m in FormTextRegex().Matches(cs))
            props[m.Groups[1].Value] = m.Groups[2].Value.Trim('"');

        foreach (Match m in ClientSizeRegex().Matches(cs))
        {
            props["ClientSize.Width"]  = m.Groups[1].Value;
            props["ClientSize.Height"] = m.Groups[2].Value;
        }

        return props;
    }

    private static (int X, int Y) ParsePoint(string val)
    {
        // "new System.Drawing.Point(10, 20)" or "10, 20"
        var nums = NumberRegex().Matches(val).Select(m => int.Parse(m.Value)).ToArray();
        return nums.Length >= 2 ? (nums[0], nums[1]) : (0, 0);
    }

    private static (int Width, int Height) ParseSize(string val)
    {
        var nums = NumberRegex().Matches(val).Select(m => int.Parse(m.Value)).ToArray();
        return nums.Length >= 2 ? (nums[0], nums[1]) : (100, 30);
    }

    private static string ConvertWinFormsColor(string wfColor)
    {
        // "System.Drawing.Color.Red" → "red"
        // "System.Drawing.Color.FromArgb(255, 0, 0)" → "rgb(255,0,0)"
        var argbMatch = ArgbRegex().Match(wfColor);
        if (argbMatch.Success)
            return $"rgb({argbMatch.Groups[1].Value},{argbMatch.Groups[2].Value},{argbMatch.Groups[3].Value})";

        var parts = wfColor.Split('.');
        return parts[^1].ToLowerInvariant();
    }

    // ──────────────────────────────────────────────────────────────────────────
    //  Event name mapping helpers
    // ──────────────────────────────────────────────────────────────────────────

    private static string MapWinFormsEventToJs(string wfEvent) =>
        wfEvent.ToLowerInvariant() switch
        {
            "click"       => "onclick",
            "doubleclick" => "ondblclick",
            "mouseenter"  => "onmouseenter",
            "mouseleave"  => "onmouseleave",
            "textchanged" => "oninput",
            "checkedchanged" => "onchange",
            "selectedindexchanged" => "onchange",
            "load"        => "onload",
            "keydown"     => "onkeydown",
            "keyup"       => "onkeyup",
            "keypress"    => "onkeypress",
            "formclosing" => "onbeforeunload",
            _ => "on" + wfEvent.ToLowerInvariant(),
        };

    private static string MapWinFormsEventToMaui(string wfEvent) =>
        wfEvent.ToLowerInvariant() switch
        {
            "click"       => "Clicked",
            "doubleclick" => "Tapped",
            "textchanged" => "TextChanged",
            "checkedchanged" => "CheckedChanged",
            "selectedindexchanged" => "SelectedIndexChanged",
            "load"        => "Loaded",
            "keydown"     => "TextChanged",
            _ => wfEvent,
        };

    // ──────────────────────────────────────────────────────────────────────────
    //  Utility
    // ──────────────────────────────────────────────────────────────────────────

    private static string HtmlEncode(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static string XmlEscape(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    // ──────────────────────────────────────────────────────────────────────────
    //  Compiled regexes
    // ──────────────────────────────────────────────────────────────────────────

    [GeneratedRegex(@"private\s+System\.Windows\.Forms\.(\w+)\s+(\w+)\s*;")]
    private static partial Regex CtrlDeclarationRegex();

    [GeneratedRegex(@"this\.(\w+)\.(\w+)\s*=\s*""?([^"";]+)""?;")]
    private static partial Regex PropAssignRegex();

    [GeneratedRegex(@"this\.(\w+)\.Font\s*=\s*new\s+\S+Font\([""']([^""']+)[""'],\s*([\d.]+)[Ff]?,\s*([^)]*)\)")]
    private static partial Regex FontRegex();

    [GeneratedRegex(@"this\.(\w+)\.(\w+)\s*\+=\s*new\s+\S*EventHandler\((\w+)\)")]
    private static partial Regex EventSubscriptionRegex();

    [GeneratedRegex(@"this\.Text\s*=\s*""([^""]+)""")]
    private static partial Regex FormTextRegex();

    [GeneratedRegex(@"this\.ClientSize\s*=\s*new\s+\S+Size\((\d+),\s*(\d+)\)")]
    private static partial Regex ClientSizeRegex();

    [GeneratedRegex(@"\d+")]
    private static partial Regex NumberRegex();

    [GeneratedRegex(@"FromArgb\((\d+),\s*(\d+),\s*(\d+)\)")]
    private static partial Regex ArgbRegex();
}

// ──────────────────────────────────────────────────────────────────────────
//  Models
// ──────────────────────────────────────────────────────────────────────────

internal enum WinFormsTarget { Html, Maui, Unity }

internal class WinFormsControl
{
    public string Type     { get; set; } = string.Empty;
    public string Name     { get; set; } = string.Empty;
    public string Text     { get; set; } = string.Empty;
    public (int X, int Y)         Location = (0, 0);
    public (int Width, int Height) Size    = (100, 30);
    public string ForeColor   { get; set; } = string.Empty;
    public string BackColor   { get; set; } = string.Empty;
    public string FontFamily  { get; set; } = "Segoe UI";
    public float  FontSize    { get; set; } = 9;
    public bool   FontBold    { get; set; }
    public bool   FontItalic  { get; set; }
    public bool   Checked     { get; set; }
    public bool   Enabled     { get; set; } = true;
    public bool   Visible     { get; set; } = true;
    public double Value       { get; set; }
    public double Minimum     { get; set; }
    public double Maximum     { get; set; } = 100;
    public bool   MultiSelect { get; set; }
    public string ImagePath   { get; set; } = string.Empty;
    public List<string>              Items  { get; } = new();
    public Dictionary<string, string> Events { get; } = new(StringComparer.OrdinalIgnoreCase);
}

/// <summary>Pascal-case helper used across converters.</summary>
internal static class NameExtensions
{
    public static string ToPascalCase(this string s)
    {
        if (string.IsNullOrEmpty(s)) return "Element";
        return char.ToUpperInvariant(s[0]) + s[1..];
    }
}
